# This is an example — replace name/namespace values for your cluster.
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: backend-tls-tcp
  namespace: agentgateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: my-llm-route
  backend:
    tls:
      # Reference a Kubernetes Secret containing TLS materials (recommended).
      # Example: secretRef points to a secret with keys "tls.crt" and "tls.key"
      secretRef:
        name: my-llm-backend-tls
        namespace: agentgateway-system
      # insecure: false prevents skipping verification (set to true only for testing)
      insecure: false
    tcp:
      keepalive:
        idle: 300s
        interval: 60s
        count: 5