#!/usr/bin/env python3
"""Write hugo-local-version.yaml: a local-only Hugo config overlay that builds
a single docs version, for a quicker `make serve VERSION=…`.

`make serve` renders every version tree under content/docs/<section>/. When you
only need one version, most of that is wasted time. This overlay adds an
`ignoreFiles` pattern for every other version directory, so Hugo never reads
those trees.

Nothing is maintained by hand. The versions come from `params.versions` in
hugo.yaml; --version takes a linkVersion (the version tree's directory name,
such as `main`, `latest`, or `2.3.x`). The overlay is gitignored and only ever
passed by the Makefile's `serve` target, never by a production build.

Links into the versions that are left out (the version dropdown, cross-version
links, blog posts that `ref` docs pages) do not resolve locally.
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG = REPO_ROOT / "hugo.yaml"
DOCS = REPO_ROOT / "content" / "docs"
OUT = REPO_ROOT / "hugo-local-version.yaml"

# Directory names that are version trees. Anything else under a section (an
# _index.md, a content adapter) is never skipped.
VERSION_DIR = re.compile(r"^(?:\d+\.\d+\.(?:x|\d+)|latest|main)$")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--version", required=True, help="the linkVersion to build")
    args = parser.parse_args()

    try:
        import yaml
    except ImportError:
        sys.exit("ERROR: VERSION needs PyYAML to read hugo.yaml. Run `pip3 install pyyaml`.")

    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8")) or {}
    entries = (config.get("params") or {}).get("versions") or []
    listed = [str(e.get("linkVersion") or e.get("version")) for e in entries]
    if args.version not in listed:
        sys.exit(
            f"ERROR: VERSION={args.version} is not a linkVersion in hugo.yaml "
            f"(have: {', '.join(listed)})"
        )
    keep = args.version

    patterns, skipped = [], []
    for section_dir in sorted(p for p in DOCS.iterdir() if p.is_dir()):
        section = section_dir.name
        for version_dir in sorted(p for p in section_dir.iterdir() if p.is_dir()):
            name = version_dir.name
            if VERSION_DIR.match(name) and name != keep:
                patterns.append(f"(^|/)content/docs/{re.escape(section)}/{re.escape(name)}/")
                skipped.append(f"{section}/{name}")

    text = (
        "# GENERATED by scripts/local-version-config.py for `make serve VERSION=…`.\n"
        "# Gitignored; never pass it to a production build.\n"
        "ignoreFiles:\n"
        + "".join(f"  - '{p}'\n" for p in patterns)
        # Pages outside the kept version (blog posts, for example) `ref` pages
        # in the skipped versions. Missing refs fail the build; warn instead.
        + "refLinksErrorLevel: warning\n"
    )
    OUT.write_text(text, encoding="utf-8")

    print(f"Building version {keep} only; skipping {', '.join(skipped) or 'nothing'}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
